//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteManagement.DB.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day : IDay
    {
        public int DayID { get; set; }
        public bool HasDelivery { get; set; }
        public int IncrementByDays { get; set; }
        public System.TimeSpan CutOff { get; set; }
        public int SiteOrderTypeID { get; set; }
        public int DateOfWeek { get; set; }
    
        public virtual SiteOrderType SiteOrderType { get; set; }
    }
}
