//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteManagement.DB.Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoutingEntities : DbContext
    {
        public RoutingEntities()
            : base("name=RoutingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteSite> RouteSites { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<SiteOrderType> SiteOrderTypes { get; set; }
    }
}
